# Generated by Django 2.1 on 2022-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('File', models.FileField(upload_to='s3://learnbay-wb/main-blog/blog/', verbose_name='file')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
