# Generated by Django 2.1 on 2022-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0003_auto_20221020_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Contact',
        ),
    ]
