# Generated by Django 2.1 on 2022-10-20 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0004_auto_20221020_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='file',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
