# Generated by Django 2.1 on 2022-10-20 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0005_auto_20221020_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='s3://learnbay-wb/main-blog/blog/', verbose_name='file'),
            preserve_default=False,
        ),
    ]
