# Generated by Django 2.1 on 2022-10-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0006_contact_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(upload_to='s3://learnbay-wb/main-blog/blog/', verbose_name=''),
        ),
    ]
