# Generated by Django 2.1 on 2022-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0007_auto_20221020_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(upload_to='public/', verbose_name=''),
        ),
    ]
