# Generated by Django 2.1 on 2022-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0008_auto_20221101_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(upload_to='s3://learnbay-wb/main-blog/blog/', verbose_name=''),
        ),
    ]
