# Generated by Django 2.1 on 2022-11-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0009_auto_20221101_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(upload_to='public/'),
        ),
    ]
