# Generated by Django 2.1 on 2022-11-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0012_auto_20221101_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
