# Generated by Django 2.1 on 2022-11-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0013_auto_20221101_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(upload_to='public/'),
        ),
    ]
