# Generated by Django 2.1 on 2022-11-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppAdmin', '0014_auto_20221114_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='file',
            new_name='file1',
        ),
    ]
